// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Alert struct {
	ID                       string
	ObjectID                 string
	Data                     pqtype.NullRawMessage
	GMag                     sql.NullFloat64
	RMag                     sql.NullFloat64
	LatestDetection          sql.NullFloat64
	FirstDetection           sql.NullFloat64
	BrighteningRate          sql.NullFloat64
	DetectionsLast7d         sql.NullInt32
	Classification           sql.NullString
	ClassificationConfidence sql.NullFloat64
	ReceivedAt               sql.NullTime
}

type Image struct {
	ID        int32
	AlertID   sql.NullString
	ImageType sql.NullString
	FilePath  string
	CreatedAt sql.NullTime
}
