// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createAlert = `-- name: CreateAlert :exec
INSERT INTO alerts (
    id, object_id, data, g_mag, r_mag,
    latest_detection, first_detection, brightening_rate,
    detections_last_7d, classification, classification_confidence
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type CreateAlertParams struct {
	ID                       string
	ObjectID                 string
	Data                     pqtype.NullRawMessage
	GMag                     sql.NullFloat64
	RMag                     sql.NullFloat64
	LatestDetection          sql.NullFloat64
	FirstDetection           sql.NullFloat64
	BrighteningRate          sql.NullFloat64
	DetectionsLast7d         sql.NullInt32
	Classification           sql.NullString
	ClassificationConfidence sql.NullFloat64
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) error {
	_, err := q.db.ExecContext(ctx, createAlert,
		arg.ID,
		arg.ObjectID,
		arg.Data,
		arg.GMag,
		arg.RMag,
		arg.LatestDetection,
		arg.FirstDetection,
		arg.BrighteningRate,
		arg.DetectionsLast7d,
		arg.Classification,
		arg.ClassificationConfidence,
	)
	return err
}

const createImage = `-- name: CreateImage :exec
INSERT INTO images (alert_id, image_type, file_path)
VALUES ($1, $2, $3)
`

type CreateImageParams struct {
	AlertID   sql.NullString
	ImageType sql.NullString
	FilePath  string
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.ExecContext(ctx, createImage, arg.AlertID, arg.ImageType, arg.FilePath)
	return err
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, object_id, data, g_mag, r_mag, latest_detection, first_detection, brightening_rate, detections_last_7d, classification, classification_confidence, received_at FROM alerts WHERE id = $1
`

func (q *Queries) GetAlertByID(ctx context.Context, id string) (Alert, error) {
	row := q.db.QueryRowContext(ctx, getAlertByID, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.Data,
		&i.GMag,
		&i.RMag,
		&i.LatestDetection,
		&i.FirstDetection,
		&i.BrighteningRate,
		&i.DetectionsLast7d,
		&i.Classification,
		&i.ClassificationConfidence,
		&i.ReceivedAt,
	)
	return i, err
}

const getImagesByAlertID = `-- name: GetImagesByAlertID :many
SELECT id, alert_id, image_type, file_path, created_at FROM images WHERE alert_id = $1
`

func (q *Queries) GetImagesByAlertID(ctx context.Context, alertID sql.NullString) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, getImagesByAlertID, alertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.ImageType,
			&i.FilePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, object_id, data, g_mag, r_mag, latest_detection, first_detection, brightening_rate, detections_last_7d, classification, classification_confidence, received_at FROM alerts
ORDER BY received_at DESC
LIMIT $1
`

func (q *Queries) ListAlerts(ctx context.Context, limit int32) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listAlerts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.Data,
			&i.GMag,
			&i.RMag,
			&i.LatestDetection,
			&i.FirstDetection,
			&i.BrighteningRate,
			&i.DetectionsLast7d,
			&i.Classification,
			&i.ClassificationConfidence,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByClassification = `-- name: ListAlertsByClassification :many
SELECT id, object_id, data, g_mag, r_mag, latest_detection, first_detection, brightening_rate, detections_last_7d, classification, classification_confidence, received_at FROM alerts
WHERE classification = $1
ORDER BY received_at DESC
LIMIT $2
`

type ListAlertsByClassificationParams struct {
	Classification sql.NullString
	Limit          int32
}

func (q *Queries) ListAlertsByClassification(ctx context.Context, arg ListAlertsByClassificationParams) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listAlertsByClassification, arg.Classification, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.Data,
			&i.GMag,
			&i.RMag,
			&i.LatestDetection,
			&i.FirstDetection,
			&i.BrighteningRate,
			&i.DetectionsLast7d,
			&i.Classification,
			&i.ClassificationConfidence,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
